name: radio_online
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audio_service: ^0.18.15
  rxdart: ^0.28.0
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  equatable: ^2.0.5
  internet_connection_checker: ^2.0.0
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.1.4
  cached_network_image: ^3.3.1
  retrofit: any
  dio: ^5.5.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ic_network_error.png
    - assets/icons/ic_radio_background.jpg
    - assets/db/