name: radio_online
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audio_service: ^0.18.15
  rxdart: ^0.28.0
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.1.4
  cached_network_image: ^3.3.1
  retrofit: any
  dio: ^5.5.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10
  scrollable_positioned_list: ^0.2.2
  flutter_launcher_icons: ^0.9.3
  connectivity_plus: ^3.0.6
  sqflite_common_ffi_web: ^0.4.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ic_network_error.png
    - assets/icons/ic_radio_background.jpg
    - assets/icons/icon.png
    - assets/db/